# permissions for end users to view memcachedbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: memcachedbackup-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: memcached-hybrid-operator
    app.kubernetes.io/part-of: memcached-hybrid-operator
    app.kubernetes.io/managed-by: kustomize
  name: memcachedbackup-viewer-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - memcachedbackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - memcachedbackups/status
  verbs:
  - get
